version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch

    working_directory: ~/
    steps:
      - run:
          name: clone and install requirements
          command: |
            set -x
            git clone https://github.com/Onther-Tech/tokamak-web-service-poc
            cd tokamak-web-service-poc
            virtualenv venv && source venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Try to reach remote server
          command: |
            ssh ubuntu@ec2-18-179-10-40.ap-northeast-1.compute.amazonaws.com <<EOF
            yes
            EOF
            pwd
            ifconfig

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
